FROM php:apache
LABEL maintainer.n1="clara.vesval@ynov.com"
LABEL maintainer.n2="jonathan.berenguer@ynov.com"
LABEL maintainer.n3="clement.charlemagne@ynov.com"
LABEL maintainer.n4="frederic.gabriel@ynov.com"
LABEL maintainer.n5="yoann.degaram@ynov.com"
LABEL maintainer.n6="helie.levydemareuil@ynov.com"

ENV USERNAME='toto'
ENV PASSWORD='python'

COPY index.php /var/www/html/index.php
WORKDIR /var/www/html

EXPOSE 80/tcp
